const showsList = [
    {
        date: 'Friday, October 21',
        time: '7:00PM',
        venue: 'The Cadieux Cafe',
        venueLink: 'https://www.cadieuxcafe.com/',
        location: '4300 Cadieux Rd, Detroit, MI 48224',
        locationLink: 'https://maps.app.goo.gl/YBTqf4EfFNcVobnV9',
        ticketLink: 'https://www.google.com/',
    },
    {
        date: 'Friday, October 21',
        time: '7:00PM',
        venue: 'The Cadieux Cafe',
        venueLink: 'https://www.cadieuxcafe.com/',
        location: '4300 Cadieux Rd, Detroit, MI 48224',
        locationLink: 'https://maps.app.goo.gl/YBTqf4EfFNcVobnV9',
        ticketLink: 'https://www.google.com/',
    },
    {
        date: 'Friday, October 21',
        time: '7:00PM',
        venue: 'The Cadieux Cafe',
        venueLink: 'https://www.cadieuxcafe.com/',
        location: '4300 Cadieux Rd, Detroit, MI 48224',
        locationLink: 'https://maps.app.goo.gl/YBTqf4EfFNcVobnV9',
        ticketLink: 'https://www.google.com/',
    },
    {
        date: 'Friday, October 21',
        time: '7:00PM',
        venue: 'The Cadieux Cafe',
        venueLink: 'https://www.cadieuxcafe.com/',
        location: '4300 Cadieux Rd, Detroit, MI 48224',
        locationLink: 'https://maps.app.goo.gl/YBTqf4EfFNcVobnV9',
        ticketLink: 'https://www.google.com/',
    },
    {
        date: 'Friday, October 21',
        time: '7:00PM',
        venue: 'The Cadieux Cafe',
        venueLink: 'https://www.cadieuxcafe.com/',
        location: '4300 Cadieux Rd, Detroit, MI 48224',
        locationLink: 'https://maps.app.goo.gl/YBTqf4EfFNcVobnV9',
        ticketLink: 'https://www.google.com/',
    },
    {
        date: 'Friday, October 21',
        time: '7:00PM',
        venue: 'The Cadieux Cafe',
        venueLink: 'https://www.cadieuxcafe.com/',
        location: '4300 Cadieux Rd, Detroit, MI 48224',
        locationLink: 'https://maps.app.goo.gl/YBTqf4EfFNcVobnV9',
        ticketLink: 'https://www.google.com/',
    },
    {
        date: 'Friday, October 21',
        time: '7:00PM',
        venue: 'The Cadieux Cafe',
        venueLink: 'https://www.cadieuxcafe.com/',
        location: '4300 Cadieux Rd, Detroit, MI 48224',
        locationLink: 'https://maps.app.goo.gl/YBTqf4EfFNcVobnV9',
        ticketLink: 'https://www.google.com/',
    },
    {
        date: 'Friday, October 21',
        time: '7:00PM',
        venue: 'The Cadieux Cafe',
        venueLink: 'https://www.cadieuxcafe.com/',
        location: '4300 Cadieux Rd, Detroit, MI 48224',
        locationLink: 'https://maps.app.goo.gl/YBTqf4EfFNcVobnV9',
        ticketLink: 'https://www.google.com/',
    },
    {
        date: 'Friday, October 21',
        time: '7:00PM',
        venue: 'The Cadieux Cafe',
        venueLink: 'https://www.cadieuxcafe.com/',
        location: '4300 Cadieux Rd, Detroit, MI 48224',
        locationLink: 'https://maps.app.goo.gl/YBTqf4EfFNcVobnV9',
        ticketLink: 'https://www.google.com/',
    },
    {
        date: 'Friday, October 21',
        time: '7:00PM',
        venue: 'The Cadieux Cafe',
        venueLink: 'https://www.cadieuxcafe.com/',
        location: '4300 Cadieux Rd, Detroit, MI 48224',
        locationLink: 'https://maps.app.goo.gl/YBTqf4EfFNcVobnV9',
        ticketLink: 'https://www.google.com/',
    },
    {
        date: 'Friday, October 21',
        time: '7:00PM',
        venue: 'The Cadieux Cafe',
        venueLink: 'https://www.cadieuxcafe.com/',
        location: '4300 Cadieux Rd, Detroit, MI 48224',
        locationLink: 'https://maps.app.goo.gl/YBTqf4EfFNcVobnV9',
        ticketLink: 'https://www.google.com/',
    },
]

export default showsList